import { ref } from 'vue';
import type { locationInterface } from './interface';

export const location = ref(null as unknown as locationInterface);
export const lastLocation = ref(null as unknown as locationInterface);

export const locations = ref([
  {
    id: "1",
    name: "bureau 🏠",
    message: 'Welcome Home 🏠',
    upper_location: 'galaxie ✨',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['0','1','2','3'],
  },
  {
    id: "2",
    name: "fin quest 1 🔥",
    message: 'Secret SPA 🔥💧🌱☁️',
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "3",
    name: "boite de nuit insectes 🪲🪩",
    message: '',
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  
  // HOLIDAYS
  {
    id: "4",
    name: "prairie 🌳",
    message: '',
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['4','5','6'],
  },
  {
    id: "5",
    name: "vac-mer 🏝️",
    message: 'Holiday World 🏝️',
    upper_location: 'prairie 🌳',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "6",
    name: "snorkeling 🐠",
    message: '',
    upper_location: 'vac-mer 🏝️',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "7",
    name: "meduses 🪼",
    message: '',
    upper_location: 'snorkeling 🐠',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "8",
    name: "monstre marin 🦕",
    message: '',
    upper_location: 'meduses 🪼',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "9",
    name: "cocciland 🐞",
    message: 'Cocciland 🐞',
    upper_location: 'vac-mer 🏝️',
    is_hidden_place: true,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "10",
    name: "carte cachette 📜",
    message: 'Treasure map 📜',
    upper_location: 'cocciland 🐞',
    is_hidden_place: true,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "11",
    name: "trésor 💰",
    message: 'You found the treasure!! 💰',
    upper_location: 'snorkeling 🐠',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "12",
    name: "cantine coccinelle 🕌",
    message: 'The Holiday House 🕌',
    upper_location: 'vac-mer 🏝️',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  
  // QUEST 3
  {
    id: "13",
    name: "ile dragon 🐉",
    message: 'Dragon Island 🐉',
    upper_location: 'cantine coccinelle 🕌',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "14",
    name: "temple 🏯",
    message: 'The Infinite Temple 🛕',
    upper_location: 'ile dragon 🐉',
    is_hidden_place: true,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },

  // SPACE
  {
    id: "15",
    name: "endding",
    message: 'THE END',
    upper_location: '',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "16",
    name: "big bang 🪐",
    message: 'Big bang 🪐',
    upper_location: 'ending',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "17",
    name: "galaxie ✨",
    message: 'Space World 💫',
    upper_location: 'big bang 🪐',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "18",
    name: "star night club ⭐️",
    message: 'Star night club ⭐️',
    upper_location: 'galaxie ✨',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "19",
    name: "coccibar 🐞",
    message: '',
    upper_location: 'galaxie ✨',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  
  // Support
  {
    id: "20",
    name: "support city 🛖",
    message: "Rock'n World 🎸",
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
  {
    id: "21",
    name: "matrix 📺",
    message: '',
    upper_location: 'support city 🛖',
    is_hidden_place: false,
    found: false,
    found_date: new Date(0),
    character: "1",
    musics: ['1','2'],
  },
] as locationInterface[]);