import { ref } from 'vue';
import type { locationInterface, locationFoundInterface } from './interface';

export const location = ref({} as locationFoundInterface);
export const lastLocation = ref({} as locationFoundInterface);

export const locations_found = ref([] as locationFoundInterface[]);

export const locations = ref([
  {
    id: "1",
    name: "bureau 🏠",
    message: 'Welcome Home 🏠',
    image_url: 'big bang 🪐',
    upper_location: 'galaxie ✨',
    is_hidden_place: false,
    musics: ['0','1','2','3'],
  },
  {
    id: "2",
    name: "fin quest 1 🔥",
    message: 'Secret SPA 🔥💧🌱☁️',
    image_url: 'big bang 🪐',
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "3",
    name: "boite de nuit insectes 🪲🪩",
    message: 'boite de nuit insectes 🪲🪩',
    image_url: 'big bang 🪐',
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  
  // HOLIDAYS
  {
    id: "4",
    name: "prairie 🌳",
    message: 'prairie 🌳',
    image_url: 'rock-world2',
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    musics: ['4','5','6'],
  },
  {
    id: "5",
    name: "vac-mer 🏝️",
    message: 'Holiday World 🏝️',
    image_url: 'big bang 🪐',
    upper_location: 'prairie 🌳',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "6",
    name: "snorkeling 🐠",
    message: 'snorkeling 🐠',
    image_url: 'Eson Island 🗿',
    upper_location: 'vac-mer 🏝️',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "7",
    name: "meduses 🪼",
    message: 'meduses 🪼',
    image_url: 'Eson Island 🗿',
    upper_location: 'snorkeling 🐠',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "8",
    name: "monstre marin 🦕",
    message: 'monstre marin 🦕',
    image_url: 'Eson Island 🗿',
    upper_location: 'meduses 🪼',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "9",
    name: "cocciland 🐞",
    message: 'Cocciland 🐞',
    image_url: 'rock-world2',
    upper_location: 'vac-mer 🏝️',
    is_hidden_place: true,
    musics: ['1','2'],
  },
  {
    id: "10",
    name: "carte cachette 📜",
    message: 'Treasure map 📜',
    image_url: 'grotte 🐳',
    upper_location: 'cocciland 🐞',
    is_hidden_place: true,
    musics: ['1','2'],
  },
  {
    id: "11",
    name: "trésor 💰",
    message: 'You found the treasure!! 💰',
    image_url: 'grotte 🐳',
    upper_location: 'snorkeling 🐠',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "12",
    name: "cantine coccinelle 🕌",
    message: 'The Holiday House 🕌',
    image_url: 'grotte 🐳',
    upper_location: 'vac-mer 🏝️',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  
  // QUEST 3
  {
    id: "13",
    name: "ile dragon 🐉",
    message: 'Dragon Island 🐉',
    image_url: 'grotte 🐳',
    upper_location: 'cantine coccinelle 🕌',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "14",
    name: "temple 🏯",
    message: 'The Infinite Temple 🛕',
    image_url: 'rock-world2',
    upper_location: 'ile dragon 🐉',
    is_hidden_place: true,
    musics: ['1','2'],
  },

  // SPACE
  {
    id: "15",
    name: "endding",
    message: 'THE END',
    image_url: 'oatly end',
    upper_location: '',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "16",
    name: "big bang 🪐",
    message: 'Big bang 🪐',
    image_url: 'oatly end',
    upper_location: 'ending',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "17",
    name: "galaxie ✨",
    message: 'Space World 💫',
    image_url: 'oatly end',
    upper_location: 'big bang 🪐',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "18",
    name: "star night club ⭐️",
    message: 'Star night club ⭐️',
    image_url: 'partager 💌',
    upper_location: 'galaxie ✨',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "19",
    name: "coccibar 🐞",
    message: 'coccibar 🐞',
    image_url: 'partager 💌',
    upper_location: 'galaxie ✨',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  
  // Support
  {
    id: "20",
    name: "support city 🛖",
    message: "Rock'n World 🎸",
    image_url: 'partager 💌',
    upper_location: 'bureau 🏠',
    is_hidden_place: false,
    musics: ['1','2'],
  },
  {
    id: "21",
    name: "matrix 📺",
    message: 'matrix 📺',
    image_url: 'rock-world2',
    upper_location: 'support city 🛖',
    is_hidden_place: false,
    musics: ['1','2'],
  },
] as locationInterface[]);